# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
     
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
   
    steps:
      - checkout
      - run: ls -alt
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
          

      - run: gradle dependencies
      - run: ls -alt

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
        
      # run tests!
      - run: gradle clean
      #- run: gradle test
      - run: gradle build
      - run: ls -alt
      - run: ls -alt ./build/libs
      #- run: aws -version
      #- run: pip install awscli --upgrade --user
      #- run: which aws
      # install python and awscli
      - run:
          name: Install dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
      - run: which aws
      - run: 
          name: s3
          command: aws s3 sync ./build/libs/*.war s3://varadbookit/artifact
 
      
   
 
       
        


